version: 2

sources:
  - name: campaigns
    description: "sample database provided by Snowflake"
    database: snowflake_sample_data
    schema: tpcds_sf10tcl
    tables:
      - name: promotion
      - name: item
      - name: date_dim