version: 2

sources:
  - name: snowflake_sample_data
    description: "sample database provided by Snowflake"
    database: snowflake_sample_data
    schema: tpcds_sf10tcl
    tables:
      - name: store_sales
        